services:

  db:
    image: postgres:11
    container_name: conduit_database
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - conduit_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/conduit-backend:latest
    container_name: backend_conduit
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - conduit_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s # give some time so that the entrypoint.sh is done
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/conduit-frontend:latest
    container_name: frontend_conduit
    restart: unless-stopped
    ports:
      - "8282:80"
    networks:
      - conduit_network
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
    name: postgres_data

networks:
  conduit_network:
    driver: bridge
